manifest:
  remotes:
      # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: steffmorse                         #new entry
      url-base: https://github.com/steffMorse  #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-mod                 #new entry
      remote: steffmorse                       #new entry
      revision: main                      #new entry
  self:
    path: config
